# dependabot-workflow

version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "datatables.net-buttons"
      - dependency-name: "datatables.net-buttons-dt"
      - dependency-name: "datatables.net-dt"
      - dependency-name: "datatables.net-plugins"
      - dependency-name: "datatables.net-responsive-dt"
      - dependency-name: "datatables.net-searchpanes"
      - dependency-name: "datatables.net-searchpanes-dt"
      - dependency-name: "datatables.net-select"
      - dependency-name: "datatables.net-select-dt"
      - dependency-name: "pdfmake"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"