name: Auto-Merge of Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from Dependabot
        if: github.actor == 'dependabot[bot]'
        run: |
          echo "PR is from Dependabot, merging..."
          gh pr merge ${{ github.event.pull_request.number }} --auto --merge
