name: Auto-Merge of Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check if PR is from Dependabot
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        run: |
          echo "PR is from Dependabot, merging..."
          gh pr merge ${{ github.event.pull_request.number }} --auto --merge
        env:
          GH_TOKEN: ${{ github.token }}
